apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gestionproductos
spec:
  rules:
  - host: myapp.com
    http:
      paths:
      - backend:
          serviceName: gestionproductos
          servicePort: 80
